### ISSUE TITLE
Assigned group to a existing user, is overwritten upon relogin

### ISSUE THREAD

**Issue by sorenmalling** [kalypsos/social_auth#2]
In the SocialAuthenticationService.php, a EXEC_updateQuery is executed if a fe_user exists and a EXEC_insertQuery if the fe_users doesn't exists.

As this is executed each time a user login (if a TYPO3 fe session cookie has expired or similar) the usergroups of a existing user get's overwritten to only have the "defaultGroup".

This should be avoided and instead check if the defaultGroup is in the groups of the already existing user - and add the defaultGroup if not present.

I will gladly provide a fix for this, so let's get to a good solution :-)

**Comment by kalypso63** [comment]
It's done. A new version (1.0.9) is present on TER which fix the default group uid on update user or use the master branch :)

**Comment by sorenmalling** [comment]
Thanks you! :-)

**Comment by sorenmalling** [comment]
Fixed in a4f624f6690bcb2e665a006c5826a4d2cddc5555
