### ISSUE TITLE
View "endpoint" can't be resolved

### ISSUE THREAD

**Issue by pahy** [kalypsos/social_auth#3]
Hi,

thanks for your work.

I am currently trying to install your extension. But all i get is following error:

> Sorry, the requested view was not found.
> 
> The technical reason is: No template was found. View could not be resolved for action "endpoint" in class "MV\SocialAuth\Controller\AuthController".

Is this my fault and what am i doing wrong?

Thanks in advance,
Patrick

**Comment by kalypso63** [comment]
Hi,

Did you follow all steps of installation and configure your social networks app ?

**Comment by pahy** [comment]
Hi,

yes. There is just google for now.

**Comment by kalypso63** [comment]
Which version of TYPO3 ?

**Comment by pahy** [comment]
Hi,
it is 7.6.12

**Comment by pahy** [comment]
Hi,
i am giving it a try again with Typo3 7.6.19 and social_auth 1.1.2. It is still the same error message. It is a completely fresh installation.

What informations do you require to help me to get it working?

Thanks in advance
Patrick
