### ISSUE TITLE
Configurable image directory

### ISSUE THREAD

**Issue by cnoelker** [kalypsos/social_auth#5]
Hello,
the SocialAuthenticationService.php contains a fixed setting of the path used for storing the profile images of users:
$path = PATH_site . 'uploads/pics/';
I think that it would be better to read the value which the user can configure:
$TCA['fe_users']['columns']['image']['config']['uploadfolder'] 
and to use the default path only if this uploadfolder is not set. Do you agree?
Claudia

**Comment by kalypso63** [comment]
Hello,

I'm agree with your fix.
It's done with the last version available on TYPO3 TER (version 1.1.1)
