### ISSUE TITLE
View "endpoint" can't be resolved

### ISSUE THREAD

**Issue by pahy** [kalypsos/social_auth#6]
Hi,
i am giving it a try again with Typo3 7.6.19 and social_auth 1.1.2. It is still the same error message like issued before. It is a completely fresh installation.

> Sorry, the requested view was not found.
> 
> The technical reason is: No template was found. View could not be resolved for action "endpoint" in class "MV\SocialAuth\Controller\AuthController".
> 

What informations do you require to help me to get it working?

Thanks in advance
Patrick

**Comment by kalypso63** [comment]
Hi,

Did you configure correctly your app (facebook, google ...)?  and params it on extension manager via TYPO3.

All fields are required on extension manger especially the Storage users tabs.

**Comment by pahy** [comment]
Hi,
yes, they are. I need google.
![image](https://user-images.githubusercontent.com/20403536/27798977-bc16d9d8-6013-11e7-8ab5-4929a84d9211.png)
![image](https://user-images.githubusercontent.com/20403536/27798985-c2392ba4-6013-11e7-9553-1bfd2a70686e.png)

and the static template is added, too!

Bye
Patrick

**Comment by pahy** [comment]
Hi,
is there anything known conflicting with social_auth?
Are there any further requirements, maybe outside typo3? A PHP library or anything else?

Thanks,
Patrick

**Comment by kalypso63** [comment]
I can't reproduce it. Did you follow all install instructions presents on README? 

Please don't fill google.providers.google.scope and retry.

**Comment by kalypso63** [comment]
Did you activate Google+ api ? 
Did you fill the field Authorized redirect uri with something like that (http://yourdomain/?type=1316773682&hauth.done=Google) ?

**Comment by pahy** [comment]
Thank you for your effort.

Yes, i followed the steps from README, google.provoders.google.scope is empty , g+ api is activated, authorized redirect uri is filled.

It redirects from

> https://mydomain/de/account/?type=1316773682

to

> https://mydomain/de/startseite/?type=1316773682

and says

> Sorry, the requested view was not found.
> 
> The technical reason is: No template was found. View could not be resolved for action "endpoint" in class "MV\SocialAuth\Controller\AuthController".

The redirect is ok for me, as long as it is working.

Do you get any other idea what i am missing?

Thanks,
Patrick

**Comment by kalypso63** [comment]
Please use the correct uri for authorized redirect uri : http://mydomain/?type=1316773682&hauth.done=Google

Don't forget hauth.done to params

**Comment by pahy** [comment]
It is:
![image](https://user-images.githubusercontent.com/20403536/27833665-0c6f393c-60d4-11e7-9da0-3684425df64b.png)

i really stuck with this and got no idea.

**Comment by kalypso63** [comment]
Test with this code on AuthController and replace current endpointAction method with

```php
/**
 * Endpoint action
 * @return void
 */
public function endpointAction()
{
    try {
        \Hybrid_Endpoint::process();
    } catch (\Exception $e) {
        throw new \Exception($e->getMessage(), 1325691094);
    }
}
```
And report me what kind of error is it

**Comment by pahy** [comment]
This is the result on https://mydomain/startseite/?type=1316773682

![image](https://user-images.githubusercontent.com/20403536/27834149-0efc5624-60d6-11e7-9945-14c92347f71f.png)

**Comment by kalypso63** [comment]
The good uri is https://mydomain/startseite/?type=1316773682&hauth.done=Google

**Comment by kalypso63** [comment]
If you dump $_REQUEST before  \Hybrid_Endpoint::process(). What do you see ? You must have hauth_start or hauth_done params

**Comment by pahy** [comment]
No, they both are missing:

```
array(1) {
  ["type"]=>
  string(10) "1316773682"
}
```

what could i check, to get 'em?

**Comment by kalypso63** [comment]
Normally nothing to do except fill the authorized redirect uri to google with hauth.done params.

How do you test the login ? With plugin (Login form) or with custom fluid ?

Install the plugin Login form on a page and on root page set on include static template social auth.

**Comment by pahy** [comment]
I just placed social_auth-plugin on an empty page - no custom fluid, no felogin. but felogin is installed. static template is included at root.

![image](https://user-images.githubusercontent.com/20403536/27835649-2dcd32d4-60dc-11e7-9e65-7669bd71a5b3.png)


I quickly tried with a Typo3 8 LTS, works out of the box like a charm. Not with this Typo3 7 LTS.

**Comment by kalypso63** [comment]
You must have an uri like this http://yourdomain/index.php?id=1&type=1316773681&tx_socialauth_pi1[provider]=google&tx_socialauth_pi1[redirect]=http:/yourdomain/index.php?id=1 on this button

**Comment by pahy** [comment]
it is:
https://mydomain/account/?type=1316773681&tx_socialauth_pi1[provider]=google&tx_socialauth_pi1[redirect]=https://mydomain/index.php?id=32

id 32 is subpage account

and it redirects directly to the ...682 page. without any google auth step.

**Comment by kalypso63** [comment]
Sorry I can't reproduce this bug with TYPO3 7 or TYPO3 8. Di you test with a Facebook app? 

Yo an also upgrade social_auth with my last release 1.1.3 present on TER

**Comment by pahy** [comment]
I upgraded the installation to typo3 8 LTS and did not change anything, except adding the scope again. Now it works perfect. Unfortunately i have absolutely no glue why it is working now.

Really a big thank you for your effort!
